services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf:/etc/nginx:ro
    depends_on:
      - todo

  todo:
    build: .
