services:
  nginx:
    image: nginx:stable
    environment:
      - ROOT_PATH=${ROOT_PATH}
    ports:
      - "80:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html:ro
      - ./nginx/conf/nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - /dev/null:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - todo

  todo:
    build: .
    environment:
      - ROOT_PATH=${ROOT_PATH}
    volumes:
      - ./data:/data
